Fix WebSocket handlers using non-existent StateEngine.load_world method
Two WebSocket handlers (handle_roll_dice, handle_update_hp) were calling:
  StateEngine.load_world(world_path)

This method doesn't exist. The correct instantiation is:
  StateEngine(world_path)

Error:
  AttributeError: type object 'StateEngine' has no attribute 'load_world'

Fixed both occurrences at lines 836 and 891. All other handlers in the file
correctly use StateEngine(world_path).